server:
    port: 8081

# 链接数据库
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/missyou?characterEncoding=utf-8&serverTimezone=GMT%2B8
        username: root
        password:

    jpa:
        properties:
            hibernate:
                show_sql: true
                format_sql: true


missyou:
    security:
        jwt-key: liyang007
        token-expire-in: 86400000
    order:
        max-ku-limit: 777