
spring:
    profiles:
        active: dev # application-dev.yml 或者 application-prod.yml
    jpa:
        hibernate:
            ddl-auto: update # model => 数据表
    jackson:
        property-naming-strategy: SNAKE_CASE # 驼峰转下划线
        serialization:
            WRITE_DATES_AS_TIMESTAMPS: true # 返回时间戳


missyou:
    api-package: com.li.missyou.api


wx:
    appid: wxb222387282c0792f
    appsecret: e5f2396991deffc32f976a2baf8429a5
    code2session: https://api.weixin.qq.com/sns/jscode2session?appid={0}&secret={1}&js_code={2}&grant_type=authorization_code